#pragma once

#include <cstdint>

namespace protocol {
namespace v1_20_4 {

constexpr std::int32_t VERSION = 765;

enum class HandshakingServerbound : std::uint8_t {
    Handshake = 0x00,
    LegacyServerListPing = 0xFE
};

enum class StatusClientbound : std::uint8_t {
    StatusResponse = 0x00,
    PongResponse = 0x01
};

enum class StatusServerbound : std::uint8_t {
    StatusRequest = 0x00,
    PingRequest = 0x01
};

enum class LoginClientbound : std::uint8_t {
    Disconnect = 0x00,
    EncryptionRequest = 0x01,
    LoginSuccess = 0x02,
    SetCompression = 0x03,
    LoginPluginRequest = 0x04,
    CookieRequest = 0x05
};

enum class LoginServerbound : std::uint8_t {
    LoginStart = 0x00,
    EncryptionResponse = 0x01,
    LoginPluginResponse = 0x02,
    LoginAcknowledged = 0x03,
    CookieResponse = 0x04
};

enum class ConfigurationClientbound : std::uint8_t {
    CookieRequest = 0x00,
    ClientboundPluginMessage = 0x01,
    Disconnect = 0x02,
    FinishConfiguration = 0x03,
    ClientboundKeepAlive = 0x04,
    Ping = 0x05,
    ResetChat = 0x06,
    RegistryData = 0x07,
    RemoveResourcePack = 0x08,
    AddResourcePack = 0x09,
    StoreCookie = 0x0A,
    Transfer = 0x0B,
    FeatureFlags = 0x0C,
    UpdateTags = 0x0D,
    KnownPacks = 0x0E,
    CustomReportDetails = 0x0F,
    ServerLinks = 0x10
};

enum class ConfigurationServerbound : std::uint8_t {
    ClientInformation = 0x00,
    CookieResponse = 0x01,
    ServerboundPluginMessage = 0x02,
    AcknowledgeFinishConfiguration = 0x03,
    ServerboundKeepAlive = 0x04,
    Pong = 0x05,
    ResourcePackResponse = 0x06,
    KnownPacks = 0x07
};

enum class PlayClientbound : std::uint8_t {
    BundleDelimiter = 0x00,
    SpawnEntity = 0x01,
    SpawnExperienceOrb = 0x02,
    EntityAnimation = 0x03,
    AwardStatistics = 0x04,
    AcknowledgeBlockChange = 0x05,
    SetBlockDestroyStage = 0x06,
    BlockEntityData = 0x07,
    BlockAction = 0x08,
    BlockUpdate = 0x09,
    BossBar = 0x0A,
    ChangeDifficulty = 0x0B,
    ChunkBatchFinished = 0x0C,
    ChunkBatchStart = 0x0D,
    ChunkBiomes = 0x0E,
    ClearTitles = 0x0F,
    CommandSuggestionsResponse = 0x10,
    Commands = 0x11,
    CloseContainer = 0x12,
    SetContainerContent = 0x13,
    SetContainerProperty = 0x14,
    SetContainerSlot = 0x15,
    CookieRequest = 0x16,
    SetCooldown = 0x17,
    ChatSuggestions = 0x18,
    ClientboundPluginMessage = 0x19,
    DamageEvent = 0x1A,
    DebugSample = 0x1B,
    DeleteMessage = 0x1C,
    Disconnect = 0x1D,
    DisguisedChatMessage = 0x1E,
    EntityEvent = 0x1F,
    Explosion = 0x20,
    UnloadChunk = 0x21,
    GameEvent = 0x22,
    OpenHorseScreen = 0x23,
    HurtAnimation = 0x24,
    InitializeWorldBorder = 0x25,
    ClientboundKeepAlive = 0x26,
    ChunkDataAndUpdateLight = 0x27,
    WorldEvent = 0x28,
    Particle = 0x29,
    UpdateLight = 0x2A,
    Login = 0x2B,
    MapData = 0x2C,
    MerchantOffers = 0x2D,
    UpdateEntityPosition = 0x2E,
    UpdateEntityPositionAndRotation = 0x2F,
    UpdateEntityRotation = 0x30,
    MoveVehicle = 0x31,
    OpenBook = 0x32,
    OpenScreen = 0x33,
    OpenSignEditor = 0x34,
    Ping = 0x35,
    PingResponse = 0x36,
    PlaceGhostRecipe = 0x37,
    PlayerAbilities = 0x38,
    PlayerChatMessage = 0x39,
    EndCombat = 0x3A,
    EnterCombat = 0x3B,
    CombatDeath = 0x3C,
    PlayerInfoRemove = 0x3D,
    PlayerInfoUpdate = 0x3E,
    LookAt = 0x3F,
    SynchronizePlayerPosition = 0x40,
    UpdateRecipeBook = 0x41,
    RemoveEntities = 0x42,
    RemoveEntityEffect = 0x43,
    ResetScore = 0x44,
    RemoveResourcePack = 0x45,
    AddResourcePack = 0x46,
    Respawn = 0x47,
    SetHeadRotation = 0x48,
    UpdateSectionBlocks = 0x49,
    SelectAdvancementTab = 0x4A,
    ServerData = 0x4B,
    SetActionBarText = 0x4C,
    SetBorderCenter = 0x4D,
    SetBorderLerpSize = 0x4E,
    SetBorderSize = 0x4F,
    SetBorderWarningDelay = 0x50,
    SetBorderWarningDistance = 0x51,
    SetCamera = 0x52,
    SetHeldItem = 0x53,
    SetCenterChunk = 0x54,
    SetRenderDistance = 0x55,
    SetDefaultSpawnPosition = 0x56,
    DisplayObjective = 0x57,
    SetEntityMetadata = 0x58,
    LinkEntities = 0x59,
    SetEntityVelocity = 0x5A,
    SetEquipment = 0x5B,
    SetExperience = 0x5C,
    SetHealth = 0x5D,
    UpdateObjectives = 0x5E,
    SetPassengers = 0x5F,
    UpdateTeams = 0x60,
    UpdateScore = 0x61,
    SetSimulationDistance = 0x62,
    SetSubtitleText = 0x63,
    UpdateTime = 0x64,
    SetTitleText = 0x65,
    SetTitleAnimationTimes = 0x66,
    EntitySoundEffect = 0x67,
    SoundEffect = 0x68,
    StartConfiguration = 0x69,
    StopSound = 0x6A,
    StoreCookie = 0x6B,
    SystemChatMessage = 0x6C,
    SetTabListHeaderAndFooter = 0x6D,
    TagQueryResponse = 0x6E,
    PickupItem = 0x6F,
    TeleportEntity = 0x70,
    SetTickingState = 0x71,
    StepTick = 0x72,
    Transfer = 0x73,
    UpdateAdvancements = 0x74,
    UpdateAttributes = 0x75,
    EntityEffect = 0x76,
    UpdateRecipes = 0x77,
    UpdateTags = 0x78
};

enum class PlayServerbound : std::uint8_t {
    ConfirmTeleportation = 0x00,
    QueryBlockEntityTag = 0x01,
    ChangeDifficulty = 0x02,
    AcknowledgeMessage = 0x03,
    ChatCommand = 0x04,
    SignedChatCommand = 0x05,
    ChatMessage = 0x06,
    PlayerSession = 0x07,
    ChunkBatchReceived = 0x08,
    ClientStatus = 0x09,
    ClientInformation = 0x0A,
    CommandSuggestionsRequest = 0x0B,
    AcknowledgeConfiguration = 0x0C,
    ClickContainerButton = 0x0D,
    ClickContainer = 0x0E,
    CloseContainer = 0x0F,
    ChangeContainerSlotState = 0x10,
    CookieResponse = 0x11,
    ServerboundPluginMessage = 0x12,
    DebugSampleSubscription = 0x13,
    EditBook = 0x14,
    QueryEntityTag = 0x15,
    Interact = 0x16,
    JigsawGenerate = 0x17,
    ServerboundKeepAlive = 0x18,
    LockDifficulty = 0x19,
    SetPlayerPosition = 0x1A,
    SetPlayerPositionAndRotation = 0x1B,
    SetPlayerRotation = 0x1C,
    SetPlayerOnGround = 0x1D,
    MoveVehicle = 0x1E,
    PaddleBoat = 0x1F,
    PickItem = 0x20,
    PingRequest = 0x21,
    PlaceRecipe = 0x22,
    PlayerAbilities = 0x23,
    PlayerAction = 0x24,
    PlayerCommand = 0x25,
    PlayerInput = 0x26,
    Pong = 0x27,
    ChangeRecipeBookSettings = 0x28,
    SetSeenRecipe = 0x29,
    RenameItem = 0x2A,
    ResourcePackResponse = 0x2B,
    SeenAdvancements = 0x2C,
    SelectTrade = 0x2D,
    SetBeaconEffect = 0x2E,
    SetHeldItem = 0x2F,
    ProgramCommandBlock = 0x30,
    ProgramCommandBlockMinecart = 0x31,
    SetCreativeModeSlot = 0x32,
    ProgramJigsawBlock = 0x33,
    ProgramStructureBlock = 0x34,
    UpdateSign = 0x35,
    SwingArm = 0x36,
    TeleportToEntity = 0x37,
    UseItemOn = 0x38,
    UseItem = 0x39
};

} // namespace v1_20_4
} // namespace protocol