name: Cross-Platform CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            compiler: gcc
            vcpkg_triplet: x64-linux
          - os: windows-latest
            compiler: msvc
            vcpkg_triplet: x64-windows
          - os: macos-latest
            compiler: clang
            vcpkg_triplet: x64-osx

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: microsoft/setup-msbuild@v1.3
      if: matrix.os == 'windows-latest'

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake boost

    - name: Setup vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install boost-system:x64-windows boost-asio:x64-windows boost-thread:x64-windows

    - name: Configure CMake (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --parallel

    - name: Test
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ParellelStone-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/bin/
          !build/bin/*.pdb